services:
  - type: web
    name: uplift-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn real_time_attribution:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0